marcelaf7/cs414-f18-001-Method-Men

Use Case Documentation.md

I am making this a pull request because I don't know if someone else is working on the document yet and don't want to mess anything up.

Add missing use case and fix numbering

---

README.md

Forgot to add myself to the readme.

Added myself to the readme file

---

Use Case Documentation.md

Altered the template, because this seems a little more intuitive.
Filled in use case R2 - Sign In.

Add R2 information to Use Case Documentation

---

Use Case Documentation.md

Fixed issues that Dr. Moreno brought up in the presentation.

Fixed problems with R1 usecase

---

Use Case Documentation.md

Added my use cases for review before merging into master.

Added R4-R6 to documentation to be critiqued.

---

Use Case Documentation.md

1. Do I have my Actors correctly [labeled]?
1. ~~Is my wording of the steps correct? Should I lump them together in one step? 
"Winner and loser are recorded" would be simpler and cleaner.~~
1. ~~Read Alt Flow and repeat the question above. This is why I worded them _backwards_. "The user that _action_ is the _actionNoun_."~~

R13 use case.md

---

.idea/codeStyles/codeStyleConfig.xml
.idea/vcs.xml
UseCaseAssign.txt
useCaseDistro.txt

Ram meeting

---

Use Case Documentation.md

Updated my use cases at the very bottom.

Update Use Case Documentation.md

---

Use Case Documentation.md

R9, R10, R11

---

Use Case Documentation.md

We used match and game interchangeably, I made it consistent.

Game -> Match

---

UseCaseDocumentation.md

Literally changed a 2 to a 3

---

UseCaseDocumentation.md

I made some major changes and they need to be reviewed

more use case compaction

---

UseCaseDocumentation.md

Just cleaned up syntax, made some small wording changes, made everything uniform/_consistent_ and added System steps between interactions of user and database.

Small Cleanup

---

client/edu/colostate/cs/cs414/MethodMen/jungle/Main.java
client/edu/colostate/cs/cs414/method_men/jungle/Main.java

* Made the directory structure and packages for the client source code.
* Added a basic hello world program so we can make sure it compiles on all out machines and because Git ignores empty directories.

Added a hello world program

---

.travis.yml

For now, Travis only checks that the client code compiles.
I will make it run the tests once we get some done.

Fix Travis to compile source code

---

Documents/Development Manual.md

1. Edited the dev manual.
2. Added information about setting up IntelliJ.
3. Changed coding convention to say "4 spaces" instead of tabs because all of our code so far is spaces.

Added development environment to the dev manual

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/NextMove.java

Change the global variables of the NextMove class to be more intuitive.
Object[] didn't make sense and I see that now.

Quick fix in NextMove

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Game.java
src/test/edu/colostate/cs/cs414/method_men/jungle/client/GameTest.java

* Modified isValidMove to now test if a Piece is trying to move into their own Den.
* The new method return true if the Piece is trying to move into their own Den.
* When the call return to isValidMove, it will return false.
* Includes Positive-confirmation test cases.
* Does not include negative-confirmation test cases, but does not require them.
- [X ] Unit Tests Passing
- [X ] Unit Tests Updated

A Piece can no longer move into their own Den

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GUI.java

* Removed the useless main method. We only have the necessary main functions now.
* Removed useless changePage method.
* I don't know what I was thinking when I wrote that changePage method. It was a bad method.

Removed main and unused method

---

Documents/Development Manual.md
run
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java

* Added run file that compiles and runs all the code in one command (only tested on Linux).
* Updated the Dev Manual with instructions on running the server.
* Added instructions on running the code via command line to Dev Manual.
* Fixed some typos and formatting things in the Dev Manual.
* I added the run file because I wanted a way to run the code from the command line.
* Also the run file might be simpler than IntelliJ's way of running both the server and client at the same time.

Added Run File and Updated Dev Manual for Server

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GUI.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/Login.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/LoginPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/RegisterPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/StartPage.java

* Created a StartPage and LoginPage that replaces the LoginDialog class. 
* Created a RegisterPage that activates when you click Register on the start page but doesn't have anything on it yet besides an cancel button
*

Zwomeldorph loginpage

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GUI.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/LoginPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/Page.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/RegisterPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/StartPage.java

* Background pics working on login and register page
*

Background pics working on login and register page

---

run
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GamePage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/LoginDialog.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/LoginPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/MainMenuPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/Register.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/Client.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientReceive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientSend.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/Login.java

Updates the main page! Check out the commit message for a full description of the changes.

jjpk-mainPageUpdate

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Board.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/Game.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/Client.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/ClientSend.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GUI.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GamePage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/LoginPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/MainMenuPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/RegisterPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/StartPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Send.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/User.java
src/test/edu/colostate/cs/cs414/method_men/jungle/client/GameTest.java

* Game state being sent to server after a valid move (still needs more info but for now its a start)
* Added socket to Game constructor to allow for sending game state
*

Working on GameState

---

src/main/edu/colostate/cs/cs414/method_men/jungle/server/SqlQueries.java

* 
- [ X] Unit Tests Passing
*

cleaned up comments

---

src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/TCPServer.java

* Login/register working
* DB connection added to server
*

server connects to DB when server runs. Login and register working

---

src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Send.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/TCPServer.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/TcpServerSocket.java

Game id and updateState added. needs invite now and createMatch

---

Documents/Development Manual.md
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GUI.java

* Updated Development Manual with new instructions on compiling and running from command line
* Updated Development Manual with new instructions on setting up IntelliJ with Maven
* Removed some unused imports from the GUI class (one of them was causing issues)

Updated Development Manual for Maven

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/MainMenuPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/OutgoingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientReceive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientSend.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Send.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/TcpServerSocket.java

Zwomeldorph loginregister

---

src/main/edu/colostate/cs/cs414/method_men/jungle/server/SqlQueries.java

pair check for match_invite

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java

* Created a function that parses the game state and changes the state of the game to whatever the string defines.
* I had to change a few things about the game state string to make this work.
* There isn't any code that runs this function to test the code:
On line 57 of the GamePage code, insert this statement:
`GameState.setGameState("BluePlayer:zane RedPlayer:steve Winner:-1 NextTurn:Red MoveCount:3 Red:7,0,0/6,0,6/4,1,1/2,1,5/1,2,0/5,2,1/3,2,4/8,2,6 Blue:8,6,0/2,6,1/3,6,3/5,6,4/1,6,6/4,7,5/6,8,0/7,8,6", game);`
* The function will return false if it cannot parse for any reason.

Parse Game State

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/OutgoingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Send.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/SqlQueries.java

* Invites working now - creates invite if no invite between two  users is currently in table
* Alerts user if invitee username does not exist, alerts with different message if pending invite between users already exists
*

made invites cry

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GUI.java

* Removed line of code that makes the window full screen (full screen only actually works on Linux, and not very well).
* Removed an unused variable in the same class.

Marcelaf remove fullscreen

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/IncomingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/OutgoingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientReceive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientSend.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java

Pending invitations now dynamically allocates in table.

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GamePage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/IncomingInvitationsPage.java
src/test/edu/colostate/cs/cs414/method_men/jungle/server/SqlUtilsTest.java

* Added accept and reject buttons to the invitations page. (they don't actually do anything yet, but there are TODO notes for everything that needs to happen

Marcelaf invitation buttons

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/IncomingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/Client.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientSend.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java

* Accept and Reject buttons working properly on IncomingInvitationsPage
*

Zwomeldorph invites

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Game.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/Player.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/CurrentGamesPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GameButton.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GameEndPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GamePage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/IncomingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/MainMenuPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Cat.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Dog.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Elephant.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Leopard.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Lion.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Rat.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Tiger.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Wolf.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientReceive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/ClientSend.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/Receive.java
src/main/edu/colostate/cs/cs414/method_men/jungle/server/SqlQueries.java

* Game state loads correctly, movement works, fixed bug associated with the first move
* We need to figure out how to make sure the user on the client can only move their assigned pieces
* Also need to display on game page and maybe also on currentGamesPage whose move it is

Zwomeldorph load game state

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Game.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/Player.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/CurrentGamesPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GamePage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/IncomingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/OutgoingInvitationsPage.java

* Refresh button on gamePage refreshes the game state
* Added info to text box about what players are in the game and whose turn it is
*

added refresh button and information on whose turn it is

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Board.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/Game.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Cat.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Dog.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Elephant.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Leopard.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Lion.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Piece.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Rat.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Tiger.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/Wolf.java

* Rewrote setGameState to delete captured pieces
* This fixes the bug where when you open a current game, captured pieces are suddenly back and at the default position.

Fix captured pieces not deleting

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Game.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/GamePage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/IncomingInvitationsPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/MainMenuPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/gui/WinnerPage.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/socket/Client.java

* Still have to click refresh button twice
*

Winner Page works for both clients

---

src/main/edu/colostate/cs/cs414/method_men/jungle/client/Board.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/GameState.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/piece/PieceFactory.java
src/main/edu/colostate/cs/cs414/method_men/jungle/client/tile/TileFactory.java
src/test/edu/colostate/cs/cs414/method_men/jungle/client/BoardTest.java
src/test/edu/colostate/cs/cs414/method_men/jungle/client/pieceTest/PieceFactoryTest.java
src/test/edu/colostate/cs/cs414/method_men/jungle/client/tileTest/MakeTileTest.java

* Moved makePiece to PieceFactory
* Moved makeTile to TileFactory
* Had to move some test cases to their own class
* Had to create some new tests

Marcelaf piece tile factory

---

Documents/Refactoring.txt

Refactoring Doc
